version: "3"

services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_DB: onboarding
      POSTGRES_USER: onboarding
      POSTGRES_PASSWORD: onboarding
    ports:
      - 5432:5432